let state={rules:null,health:null};const $=id=>document.getElementById(id);const saved=JSON.parse(localStorage.getItem("cardwise-settings")||"{}");
function save(){localStorage.setItem("cardwise-settings",JSON.stringify({activated:$("discoverActivated").checked,spend:Number($("discoverSpend").value||0),executive:$("costcoExecutive").checked}))}
function adjust(cat){let c=JSON.parse(JSON.stringify(cat)),sp=Number($("discoverSpend").value||0),a=$("discoverActivated").checked;if(c.cap&&(c.cap.kind==="discover_q3"||c.cap.kind==="multi")){if(!a||sp>=1500){c.ranked=c.ranked.filter(x=>x.card!=="discover");c.cap.text+=!a?" Discover is marked NOT activated.":" You marked the $1,500 cap as reached."}else c.cap.text+=` Remaining Discover tracked capacity: $${Math.max(0,1500-sp).toFixed(0)}.`}if(c.id==="costco_wholesale"&&!$("costcoExecutive").checked)delete c.side_reward;return c}
function ct(c){return c==="high"?"High confidence":c==="category-dependent"?"Merchant-code dependent":c==="medium"?"Verify issuer category":c||""}
function render(){if(!state.rules)return;save();let o=state.rules.categories.find(c=>c.id===$("category").value)||state.rules.categories[0],c=adjust(o),b=c.ranked[0],s=c.ranked[1],cards=state.rules.cards;$("bestName").textContent=cards[b.card].name;$("bestRate").textContent=b.rate+"%";$("bestNote").textContent=b.note;$("bestConfidence").textContent=ct(b.confidence);$("secondName").textContent=cards[s.card].name;$("secondRate").textContent=s.rate+"%";$("secondNote").textContent=s.note;$("secondConfidence").textContent=ct(s.confidence);
let x=$("capBox");if(c.cap){x.classList.remove("hidden");x.innerHTML="<b>CAP / LIMIT</b><br>"+c.cap.text}else x.classList.add("hidden");
x=$("sideReward");if(c.side_reward){x.classList.remove("hidden");x.innerHTML="<b>SEPARATE REWARD</b><br>"+c.side_reward}else x.classList.add("hidden");
x=$("exceptionsBox");if(c.exceptions?.length){x.classList.remove("hidden");x.innerHTML="<b>EXCEPTIONS / WATCH-OUTS</b><ul>"+c.exceptions.map(v=>"<li>"+v+"</li>").join("")+"</ul>"}else x.classList.add("hidden")}
function renderHealth(){let h=state.health;if(!h){$("sourceStatus").textContent="No health file yet";$("health").innerHTML='<p class="muted">GitHub Actions has not written the first source check yet.</p>';return}$("sourceStatus").textContent=h.ok?"Official sources checked":"Some sources need review";$("health").innerHTML='<p class="muted">Last automatic check: '+new Date(h.checked_at).toLocaleString()+"</p>"+h.sources.map(s=>`<div class="health-row"><span>${s.label}</span><span class="${s.ok?'ok':'warn'}">${s.ok?'reachable / marker found':'review needed'}</span></div>`).join("")}
async function loadHealth(){try{let r=await fetch("data/source_health.json?x="+Date.now(),{cache:"no-store"});if(!r.ok)throw 0;state.health=await r.json()}catch(e){state.health=null}renderHealth()}
async function load(){state.rules=await(await fetch("data/rules.json?x="+Date.now(),{cache:"no-store"})).json();$("asof").textContent=`${state.rules.month_label} • rules snapshot ${state.rules.as_of} • 1 point = 1¢ minimum cash-equivalent`;$("category").innerHTML=state.rules.categories.map(c=>`<option value="${c.id}">${c.label}</option>`).join("");$("discoverActivated").checked=saved.activated??true;$("discoverSpend").value=saved.spend??0;$("costcoExecutive").checked=saved.executive??true;$("sources").innerHTML=state.rules.sources.map(s=>`<div class="source"><b>${s.label}</b><div class="muted">${s.supports}</div><a href="${s.url}" target="_blank" rel="noopener noreferrer">${s.url}</a></div>`).join("");render();loadHealth()}
["category","discoverActivated","discoverSpend","costcoExecutive"].forEach(id=>$(id).addEventListener("change",render));$("refreshBtn").addEventListener("click",loadHealth);if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});load();