const $=s=>document.querySelector(s);let rules;
const state={active:localStorage.getItem('discoverActive')==='true',spend:Number(localStorage.getItem('discoverSpend')||0),executive:localStorage.getItem('costcoExecutive')!=='false'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function json(path,refresh=false){const url=refresh?`${path}?v=${Date.now()}`:path;const r=await fetch(url,{cache:refresh?'no-store':'default'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
function dateLabel(value){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.valueOf())?value:new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(d)}
async function loadHealth(refresh=false){const feedback=$('#health-feedback');feedback.textContent=refresh?'Checking for the newest published result…':'';try{const h=await json('data/source_health.json',refresh);const sources=h.sources||[];const bad=sources.filter(s=>!s.ok).length;$('#health-summary').textContent=bad?`${bad} of ${sources.length} sources need review`:`${sources.length} official sources look healthy`;$('#last-checked').textContent=`Last checked: ${dateLabel(h.checked_at)}`;feedback.textContent=refresh?`Reloaded at ${new Date().toLocaleTimeString()}.`:''}catch(e){$('#health-summary').textContent='Health file unavailable';$('#last-checked').textContent='Last checked: unavailable';feedback.textContent='Could not reload the published check. Try again after GitHub Pages finishes publishing.'}}
function score(category){const c=rules.categories.find(x=>x.id===category);let options=c.options.map(x=>({...x}));if(category==='discover_quarterly')options=options.filter(x=>x.card!=='Discover it'||(state.active&&state.spend<1500));options.sort((a,b)=>b.rate-a.rate||(a.chase?-1:1));return {c,options}}
function render(){const {c,options}=score($('#category').value);const amount=Number($('#amount').value||0);const shown=options.slice(0,2);$('#recommendations').innerHTML=`<div class="ranks">${shown.map((o,i)=>`<article class="rank ${i?'':'first'}"><div class="place">${i?'Second choice':'Best choice'}</div><div class="card">${esc(o.card)}</div><div class="rate">${esc(o.label||`${o.rate}%`)}</div>${amount?`<p>About <strong>$${(amount*o.rate/100).toFixed(2)}</strong> in cash-equivalent rewards</p>`:''}<p class="reason">${esc(o.reason)}</p>${o.cap?`<span class="cap">⚠ ${esc(o.cap)}</span>`:''}</article>`).join('')}</div>`;let notes=[...(c.exceptions||[])];if(c.id==='costco_wholesale'&&state.executive)notes.unshift('Costco Executive: add approximately 2% on qualifying warehouse purchases.');if(c.id==='costco_gas')notes.unshift('Costco Executive 2% does not apply to gasoline.');if(c.id==='discover_quarterly')notes.unshift(`Discover tracked spend: $${state.spend.toFixed(0)} of $1,500 quarterly cap; activation ${state.active?'on':'off'}.`);$('#exceptions').innerHTML=notes.map(n=>`<li>${esc(n)}</li>`).join('')}
async function init(){rules=await json('data/rules.json');$('#category').innerHTML=rules.categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');$('#discover-active').checked=state.active;$('#discover-spend').value=state.spend||'';$('#costco-executive').checked=state.executive;const workflow=rules.config?.github_actions_url;if(workflow){$('#run-check').href=workflow;$('#run-check').hidden=false}['category','amount'].forEach(id=>$(`#${id}`).addEventListener('input',render));$('#discover-active').addEventListener('change',e=>{state.active=e.target.checked;localStorage.setItem('discoverActive',state.active);render()});$('#discover-spend').addEventListener('input',e=>{state.spend=Number(e.target.value||0);localStorage.setItem('discoverSpend',state.spend);render()});$('#costco-executive').addEventListener('change',e=>{state.executive=e.target.checked;localStorage.setItem('costcoExecutive',state.executive);render()});$('#reload-health').addEventListener('click',()=>loadHealth(true));render();loadHealth()}
init().catch(()=>{$('#recommendations').textContent='Could not load CardWise rules.'});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
